version: '3'
services:
  db:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: test123++
      MYSQL_DATABASE: businessdb
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql # Chemin relatif vers le script SQL
    networks:
      - my_network

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile # Spécifiez le Dockerfile dans backend
      container_name: app-container
    environment:
      DB_HOST: db-container
      DB_USER: root
      DB_PASSWORD: test123++
      DB_NAME: businessdb
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "80:80" # Mappez le port 80 de l'hôte vers le conteneur

networks:
  my_network:
    driver: bridge
