---
- name: Setup web servers
  hosts: ubuntu
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/
